export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  PAINEL: "/painel",
  DASHBOARD: "/painel/dashboard",
  CONVERSAS: "/painel/conversas",
  LEADS: "/painel/leads",
  PROJETOS: "/painel/projetos",
  TAREFAS: "/painel/tarefas",
  DISPAROS: "/painel/disparos",
  RECORRENTES: "/painel/recorrentes",
  NOTIFICAR: "/painel/notificar",
  FINANCEIRO: "/painel/financeiro",
  AGENTES: "/painel/agentes",
  EQUIPE: "/painel/equipe",
  TESTERS: "/painel/testers",
  TESTERS_CADASTROS: "/painel/testers/cadastros",
  CONFIGURACOES: "/painel/configuracoes",

  API_AUTH_LOGIN: "/api/auth/login",
  API_AUTH_LOGOUT: "/api/auth/logout",
  API_AUTH_TOKEN: "/api/auth/token",
  API_AUTH_REFRESH: "/api/auth/refresh",
  API_AUTH_ME: "/api/auth/me",
  API_WHATSAPP_SEND: "/api/whatsapp/send",
  API_WHATSAPP_WEBHOOK: "/api/whatsapp/webhook",
  API_LEADS: "/api/leads",
  API_CONVERSAS: "/api/conversas",
  API_DISPAROS: "/api/disparos",
  API_RECORRENTES: "/api/recorrentes",
  API_NOTIFICAR: "/api/notificar",
  API_FINANCEIRO: "/api/financeiro",
  API_AGENTES: "/api/agentes",
  API_EQUIPE: "/api/equipe",
  API_PROJETOS: "/api/projetos",
  API_TAREFAS: "/api/tarefas",
  API_CONFIGURACOES: "/api/configuracoes",
} as const

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES]

export const PANEL_ROUTES = [
  ROUTES.DASHBOARD,
  ROUTES.CONVERSAS,
  ROUTES.LEADS,
  ROUTES.PROJETOS,
  ROUTES.TAREFAS,
  ROUTES.DISPAROS,
  ROUTES.RECORRENTES,
  ROUTES.NOTIFICAR,
  ROUTES.FINANCEIRO,
  ROUTES.AGENTES,
  ROUTES.EQUIPE,
  ROUTES.TESTERS,
  ROUTES.CONFIGURACOES,
] as const
