export const WHATSAPP_BROADCAST_TOPIC = "crm-whatsapp-broadcast"
export const WHATSAPP_BROADCAST_MIN_DELAY_SECONDS = 5
export const WHATSAPP_BROADCAST_MAX_DELAY_SECONDS = 10
export const WHATSAPP_BROADCAST_MAX_BATCH_SIZE = Number(process.env.NEXT_PUBLIC_WHATSAPP_BROADCAST_MAX_BATCH_SIZE ?? process.env.WHATSAPP_BROADCAST_MAX_BATCH_SIZE ?? 40)
export const WHATSAPP_BROADCAST_MAX_PER_HOUR = Number(process.env.NEXT_PUBLIC_WHATSAPP_BROADCAST_MAX_PER_HOUR ?? process.env.WHATSAPP_BROADCAST_MAX_PER_HOUR ?? 60)
export const WHATSAPP_BROADCAST_AUTO_PAUSE_FAILURES = Number(process.env.NEXT_PUBLIC_WHATSAPP_BROADCAST_AUTO_PAUSE_FAILURES ?? process.env.WHATSAPP_BROADCAST_AUTO_PAUSE_FAILURES ?? 5)
